Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ret.convert_pandas()

# 観測値, 状態変数 (ローカル・トレンド) のプロット.
fig = plt.figure(figsize=(24, 12))

# 観測値
ax1 = fig.add_subplot(411)
ret.endog.plot(ax=ax1, label="Simulated observations")

# トレンド
ax2 = fig.add_subplot(412)
ret.trend.plot(ax=ax2, label="Trend")

# シーズン性
ax3 = fig.add_subplot(413)
ret.freq_seasonal.sum(axis=1).plot(ax=ax3, label="Seasonality")

# 回帰成分
ax4 = fig.add_subplot(414)
ret.reg.sum(axis=1).plot(ax=ax4, label="Regression")

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [14][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mret[49m[38;5;241;43m.[39;49m[43mconvert_pandas[49m()
[1;32m      3[0m [38;5;66;03m# 観測値, 状態変数 (ローカル・トレンド) のプロット.[39;00m
[1;32m      4[0m fig [38;5;241m=[39m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m24[39m, [38;5;241m12[39m))

[0;31mAttributeError[0m: 'Bunch' object has no attribute 'convert_pandas'
AttributeError: 'Bunch' object has no attribute 'convert_pandas'

